{{- if and (hasKey .Values "service") (hasKey .Values.service "enabled") (eq .Values.service.enabled true) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "storj-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "storj-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "storj-gateway.selectorLabels" . | nindent 4 }}
{{- end }}
