{{- if and (hasKey .Values "configMap") (typeIs "map[string]interface {}" .Values.configMap) }}
  {{- $cfg := .Values.configMap }}
  {{- if and (hasKey $cfg "enabled") (eq $cfg.enabled true) (hasKey $cfg "data") (gt (len $cfg.data) 0) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cfg.name | default (printf "%s-config" (include "storj-gateway.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "storj-gateway.labels" . | nindent 4 }}
data:
{{- range $filename, $content := $cfg.data }}
  {{ $filename | quote }}: |
{{ $content | indent 4 }}
{{- end }}
  {{- end }}
{{- end }}
