{{- if and (hasKey .Values "persistence") (hasKey .Values.persistence "enabled") (eq .Values.persistence.enabled true) (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "storj-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "storj-gateway.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
{{- end }}
