{{- if and (hasKey .Values "serviceAccount") (hasKey .Values.serviceAccount "create") (eq .Values.serviceAccount.create true) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "storj-gateway.serviceAccountName" . | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "storj-gateway.labels" . | nindent 4 }}
{{- end }}
