{{- if .Values.rollout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "storj-gateway.fullname" . }}-active
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "storj-gateway.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "storj-gateway.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
{{- end }}