replicaCount: 1

image:
  repository: docker.io/storjlabs/gateway
  tag: 1d044e7-v1.10.0-go1.23.4
  pullPolicy: Always

persistence:
  enabled: true
  existingClaim: storj-config-pvc-test-01
  create: false
  accessMode: ReadWriteOnce
  size: 5Mi
  storageClassName: ""
  mountPath: /root/.local/share/storj/gateway

volumeMounts:
  - mountPath: /root/.local/share/storj/gateway
    name: storj-config
  - mountPath: /etc/storj-config
    name: storj-configmap

envConfigMap:
  enabled: true
  name: storj-env-config
  data:
    STORJ_ACCESS: REPLACE_WITH_ACCESS
    STORJ_KEY: REPLACE_WITH_ACCESS_KEY
    STORJ_SECRET: REPLACE_WITH_SECRET_KEY

configMap:
  enabled: true
  name: storj-gateway-config
  defaultMode: 420
  mountPath: /etc/storj-config
  data:
    config.yaml: |
      access: REPLACE_WITH_ACCESS
      minio.access-key: REPLACE_WITH_ACCESS_KEY
      minio.secret-key: REPLACE_WITH_SECRET_KEY

initContainer:
  enabled: true
  name: copy-config
  image: busybox
  pullPolicy: Always
  command:
    - /bin/sh
    - -c
  args:
    - cp -f /etc/storj-config/config.yaml /root/.local/share/storj/gateway/config.yaml
  volumeMounts:
    - mountPath: /root/.local/share/storj/gateway
      name: storj-config
    - mountPath: /etc/storj-config
      name: storj-configmap
  resources:
    requests:
      cpu: "25m"
      memory: "32Mi"
    limits:
      cpu: "50m"
      memory: "64Mi"

command:
  - /bin/sh
  - "-c"

args:
  - exec /entrypoint run --access "$STORJ_ACCESS" --minio.access-key "$STORJ_KEY" --minio.secret-key "$STORJ_SECRET"

service:
  enabled: true
  type: ClusterIP
  port: 7777
  targetPort: 7777

serviceAccount:
  create: true
  name: storj-gateway

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

podSecurityContext: {}
