name: GitHub Release

on:
  push:
    tags:
      - "v*"

jobs:
  generate-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up git-cliff
        uses: taiki-e/install-action@v2
        with:
          tool: git-cliff

      - name: Generate changelog
        run: git cliff --tag ${{ github.ref_name }} -o CHANGELOG.md

      - name: Commit changelog (forced)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -f CHANGELOG.md
          git commit -m "docs: update changelog for ${{ github.ref_name }}" || echo "No changes to commit"
          git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: CHANGELOG.md