name: Helm Chart Validation

on:
  push:
    branches:
      - 'feat/**'
      - 'fix/**'
      - 'chore/**'
      - 'refactor/**'
  pull_request:
    paths:
      - 'storj-gateway/**'
      - 'Makefile'
      - '.github/workflows/helm-validate.yml'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Lint chart
        run: make lint

      - name: Render templates
        run: make template

